secret:
    data: ENC[AES256_GCM,data:5KZU8WWV/Gr3h+3WS6amgoU7N24sTl2qgw+o/TrVY/Dvzw==,iv:AbfXRebxA4KhWzBj3ysQ2J0WyJM049nsli9Vc5o6Bc8=,tag:qwCu3lxJpFO5+D+R8jNPeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2023-07-31T12:16:17Z'
    mac: ENC[AES256_GCM,data:cwU/3O5AQeAh12p6eAuNTWFFRq9GeKiXvcx1nuf9C3zexzXMkuLmYvdkN/WGDu8yMK2lGRHjRKNORO6F0d8ilIPmOFJ9UwiCYIsLdiEz81Rzib1FgZ5qZOGYmsyk+o8sN6Bx4FP8aumdzuK8ujRlteKnA8BDy4KUXCFQ+EqPISA=,iv:bFVMckDiYQYXdFVTbJrXoFs7lgF6MORcHk5e//Fv54I=,tag:LFdEYNR9fxNO6bWMo1yymQ==,type:str]
    pgp:
    -   created_at: '2023-07-31T12:16:17Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8/syKVwDMcVAQv+Nya2dE0YpEroysJhTPNvg0O13qJAN17P9wJ9RsroL8Yx
            45Npo/rXpT/P1IXKrQKTJxVgzgnmfZdv4AkI1HoWf9/Z+OgIrZCfXDE2fOPuHdJH
            e76iUG16IVWMMkijApwBCqt6YhoJdRSaoKzlFoWHsrsRCk2nrKbt7M12kzfmxGpy
            IDaHMIO4BQlRr6ylWyHb3ElPG12JRDdYQ0iMt4MHH0w897sB9YridtQ9pPeIdlK6
            57xAewTLPkEQIPcgGp1NamTR+h85HblsGTKv418nz1UdX0slGWlygvxe+gBFnsxD
            y8KQ9dPY/8rCtYKB2vxRDWsrGRzl34aEQ5UOaQ/5ES1ir9U6TfTtOGOfw9ddwP/L
            9ffJnVZmhlPsRafG4a/bxpS/tzv6m3IfXaMFnPWV2AYhliFSLOTG7fCh0EfLLuVD
            CLrpfGLaWKO71C5Xc4gXy4mEeWjUEIcdDNL5gFOX7t+uFZxdbmJofXccSlm7HZ4R
            q8tNuIKzoaf80UYICNV90lwBKcXlITYjTdLUakGb0PZnlnEc24pwYzTxsbNVT5pC
            pr4SJhwhMrIKNB+sqF8PJ/H0bmngiQoHHGlq8TvuDvU419CdOBMERobd9as1kUuZ
            YfdxtxOPOLM8xBAKWw==
            =XIP5
            -----END PGP MESSAGE-----
        fp: F59BF29173FB19AD8182824901D477AFBCF8E510
    unencrypted_suffix: _unencrypted
    version: 3.0.3
