apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespase: {{ .Values.namespase }}
type: Opaque
data:
  ENVIRONMENT_FROM_SECRET: {{ .Values.secret.data.ENVIRONMENT_FROM_SECRET | b64enc | quote }}