apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  {{- template "mychart.labels" . }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.portNumber }}
    targetPort: {{ .Values.container.portName | quote }}
  selector:
    {{- include "selectorLabels" . | indent 2 }}
  type: ClusterIP