apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.service.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.portNumber }}
    targetPort: {{ .Values.container.portName }}
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP