configmap:
  data:
    ENVIRONMENT: default

image:
  pullSecrets: ghcr-login-secret
  name: ghcr.io/jokerwrld999/python-webapp
  tag: latest

container:
  portName: pod-custom-port
  portNumber: 8000

service:
  portNumber: 9999

ingress:
  className: nginx

clusterissuer:
  email: ifalaleev49@gamil.com
