appName: python-webapp

namespace: default

configmap:
  name: helmappconfigmapv1.0
  data:
    ENVIRONMENT: default

secret:
  name: secretv1.0

image:
  pullSecrets: ghcr-login-secret
  name: ghcr.io/jokerwrld999/python-webapp
  tag: latest

container:
  name: python-webapp-container
  portName: http-web-svc
  portNumber: 8000

service:
  name: python-webapp-svc
  portNumber: 9999