{{ if ne .Release.Namespace "dev" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-clusterissuer
  {{- template "labels" . }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.clusterissuer.server | quote }}
    # Email address used for ACME registration
    email: {{ .Values.clusterissuer.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: "{{ .Release.Name }}-tls"
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className | quote }}
{{ end }}