apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  {{- template "labels" . }}
type: Opaque
data:
  ENVIRONMENT_FROM_SECRET: {{ .Values.secret.data.ENVIRONMENT_FROM_SECRET | b64enc | quote }}